[package]
authors = ["ixsetf"]
build = "build.rs"
edition = "2018"
name = "rustmania"
version = "0.1.0"

[dependencies]
clap = "2.32.0"
cpal = "0.8.2"
hound = "3.4.0"
lazy_static = "1.3.0"
lewton = "0.9.1"
minimp3 = "0.3.0"
nom = "4.1.0"
regex = "1"
serde = "1.0.79"
serde_derive = "1.0.79"
toml = "0.4.8"
rayon = "1.0.3"
rand = "0.6.5"
bincode = "1.1.2"
serde_yaml = "0.8.8"
log = "0.4"
fern = "0.5"

[dependencies.ggez]
git = "https://github.com/ggez/ggez.git"

[dependencies.num-rational]
version = "0.2"
default-features = false
features = ["std", "bigint-std", "serde"]